export const config = {
  NOTION_API_KEY: process.env.NOTION_API_KEY,
  OPENAI_API_KEY: process.env.OPENAI_API_KEY,
  OPENAI_BASEPATH: process.env.OPENAI_BASEPATH,
  NOTION_PROMPT_DATABASE_ID: process.env.NOTION_PROMPT_DATABASE_ID
}
