export const config = {
  OPENAI_API_KEY: process.env.OPENAI_API_KEY,
  OPENAI_BASEPATH: process.env.OPENAI_BASEPATH,
  OPENAI_TAG_ASSISTANT: process.env.OPENAI_TAG_ASSISTANT,
  NOTION_API_KEY: process.env.NOTION_API_KEY,
  NOTION_PROMPT_DATABASE_ID: process.env.NOTION_PROMPT_DATABASE_ID,
  NOTION_MESSAGES_DATABASE_ID: process.env.NOTION_MESSAGES_DATABASE_ID
}
